name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 240
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: .
          retention-days: 30

  push:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: gh-pages
          path: gh-pages

      - id: hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ steps.hash.outputs.hash != github.event.before }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
